#include "ump/KaviroCore.h"
#include <cstdio>
#include <array>
#include <cstdlib>
#include <sstream>
#ifdef _WIN32
#define KAVIRO_POPEN _popen
#define KAVIRO_PCLOSE _pclose
#else
#define KAVIRO_POPEN popen
#define KAVIRO_PCLOSE pclose
#endif
namespace {
std::string q(const std::string& s) {
#ifdef _WIN32
    std::string r = "\"";
    for (char c : s) {
        if (c == '\"') r += "\\\"";
        else r += c;
    }
    return r + "\"";
#else
    std::string r = "'";
    for (char c : s) {
        if (c == '\'') r += "'\\\\''";
        else r += c;
    }
    return r + "'";
#endif
}

bool ex(sqlite3* d, const char* s) {
    return sqlite3_exec(d, s, nullptr, nullptr, nullptr) == SQLITE_OK;
}
}
namespace ump{
std::string mediaTypeName(MediaType t){return t==MediaType::Video?"video":t==MediaType::Audio?"audio":"unknown";}std::string titleFromPath(const std::filesystem::path&p){return p.stem().string();}std::string stableMediaId(const std::filesystem::path&p){std::error_code e;auto c=std::filesystem::weakly_canonical(p,e);return std::to_string(std::hash<std::string>{}((e?p.lexically_normal():c).generic_string()));}
MediaProbeResult MediaProbe::inspect(const std::string&p){MediaProbeResult r;std::string cmd="ffprobe -v error -show_entries format=format_name,duration,bit_rate:stream=codec_type,codec_name,width,height -of default=noprint_wrappers=1:nokey=0 -- "+q(p)+" 2>&1";FILE*f=KAVIRO_POPEN(cmd.c_str(),"r");if(!f){r.error="ffprobe unavailable";return r;}std::array<char,4096>b{};std::string o;while(fgets(b.data(),b.size(),f))o+=b.data();int rc=KAVIRO_PCLOSE(f);if(rc){r.error=o.empty()?"ffprobe failed":o;return r;}std::istringstream in(o);std::string l,c;bool v=false,a=false;while(std::getline(in,l)){auto n=l.find('=');if(n<1)continue;auto k=l.substr(0,n),x=l.substr(n+1);if(k=="format_name")r.format=x;else if(k=="duration")r.durationMs=std::max<std::int64_t>(0,(std::int64_t)(std::atof(x.c_str())*1000));else if(k=="bit_rate")r.bitrate=std::max<std::int64_t>(0,std::atoll(x.c_str()));else if(k=="codec_type"){v|=x=="video";a|=x=="audio";}else if(k=="codec_name"&&c.empty())c=x;else if(k=="width")r.width=std::max(0,std::atoi(x.c_str()));else if(k=="height")r.height=std::max(0,std::atoi(x.c_str()));}r.codec=c;r.type=v?MediaType::Video:a?MediaType::Audio:MediaType::Unknown;r.success=r.type!=MediaType::Unknown;if(!r.success)r.error="No audio/video stream detected";return r;}
std::vector<MediaItem>MediaLibrary::scan(const std::filesystem::path&r,const Progress&p){ScanDiagnostics d;return scanDetailed(r,d,p);}std::vector<MediaItem>MediaLibrary::scanDetailed(const std::filesystem::path&r,ScanDiagnostics&d,const Progress&p){items_.clear();cancelled_=false;std::error_code e;if(!std::filesystem::exists(r,e)||e){++d.traversalErrors;d.errors.push_back("Root missing or inaccessible");return items_;}std::unordered_set<std::string>seen;std::filesystem::recursive_directory_iterator it(r,std::filesystem::directory_options::skip_permission_denied,e),end;for(;it!=end&&!cancelled_;it.increment(e)){if(e){++d.traversalErrors;e.clear();continue;}if(!it->is_regular_file(e)){e.clear();continue;}++d.filesVisited;auto pth=it->path();auto key=std::filesystem::weakly_canonical(pth,e).generic_string();e.clear();if(!seen.insert(key).second)continue;++d.candidates;auto probe=MediaProbe::inspect(pth.string());if(!probe.success){++d.inspectionFailures;continue;}items_.push_back({stableMediaId(pth),pth,titleFromPath(pth),probe.format,probe.type,probe.durationMs});++d.detectedMedia;if(p)p(pth,d.filesVisited);}return items_;}void MediaLibrary::cancel(){cancelled_=true;}bool MediaLibrary::cancelled()const{return cancelled_;}const std::vector<MediaItem>&MediaLibrary::items()const{return items_;}
bool ExternalPlayerAdapter::play(const std::string&p){if(p.empty())return false;state_=EngineState::Playing;return true;}bool ExternalPlayerAdapter::pause(){if(state_!=EngineState::Playing)return false;state_=EngineState::Paused;return true;}bool ExternalPlayerAdapter::seek(std::int64_t p){return p>=0;}bool ExternalPlayerAdapter::setSpeed(double s){return std::isfinite(s)&&s>=.25&&s<=4;}bool ExternalPlayerAdapter::setVolume(int v){return v>=0&&v<=100;}bool ExternalPlayerAdapter::stop(){state_=EngineState::Stopped;return true;}bool ExternalPlayerAdapter::isPlaying()const{return state_==EngineState::Playing;}EngineState ExternalPlayerAdapter::state()const{return state_;}bool ExternalPlayerAdapter::supports(EngineCapability c)const{return c==EngineCapability::Pause||c==EngineCapability::Seek||c==EngineCapability::Speed||c==EngineCapability::Volume;}MediaEngineInfo ExternalPlayerAdapter::info()const{MediaEngineInfo i;i.backend=EngineBackend::ExternalDevelopment;i.name="ffplay development adapter";i.version="system";i.available=true;i.standalone=false;i.notes={"Development-only adapter; final releases must bundle a native engine."};return i;}std::unique_ptr<PlaybackEngine>MediaEngineFactory::createDevelopmentEngine(){return std::make_unique<ExternalPlayerAdapter>();}std::unique_ptr<PlaybackEngine>MediaEngineFactory::createBundledEngine(){return nullptr;}std::unique_ptr<PlaybackEngine>MediaEngineFactory::createBestAvailableEngine(){return createDevelopmentEngine();}
PlaybackState sanitizePlaybackState(PlaybackState s,std::int64_t d){s.positionMs=std::max<std::int64_t>(0,s.positionMs);if(d>0)s.positionMs=std::min(s.positionMs,d);if(!std::isfinite(s.speed))s.speed=1;s.speed=std::clamp(s.speed,.25,4.0);s.volume=std::clamp(s.volume,0,100);return s;}bool PlaybackController::load(const std::string&p,std::int64_t d){if(p.empty()||d<0)return false;path_=p;durationMs_=d;positionMs_=0;playing_=false;return true;}bool PlaybackController::play(){if(path_.empty())return false;playing_=true;return true;}bool PlaybackController::pause(){if(!playing_)return false;playing_=false;return true;}bool PlaybackController::stop(){if(path_.empty())return false;playing_=false;positionMs_=0;return true;}bool PlaybackController::seek(std::int64_t p){if(path_.empty()||p<0)return false;positionMs_=durationMs_?std::min(p,durationMs_):p;return true;}bool PlaybackController::setSpeed(double s){if(!std::isfinite(s))s=1;if(s<.25||s>4)return false;speed_=s;return true;}bool PlaybackController::setVolume(int v){if(v<0||v>100)return false;volume_=v;return true;}const std::string&PlaybackController::path()const{return path_;}std::int64_t PlaybackController::positionMs()const{return positionMs_;}double PlaybackController::speed()const{return speed_;}int PlaybackController::volume()const{return volume_;}bool PlaybackController::playing()const{return playing_;}
PlaybackStore::PlaybackStore(const std::string&p):path_(p){}PlaybackStore::~PlaybackStore(){if(db_)sqlite3_close(db_);}bool PlaybackStore::open(){if(sqlite3_open(path_.c_str(),&db_)!=SQLITE_OK)return false;sqlite3_busy_timeout(db_,3000);return ex(db_,"CREATE TABLE IF NOT EXISTS playback_state(media_id TEXT PRIMARY KEY,position_ms INTEGER,speed REAL,volume INTEGER,paused INTEGER);");}bool PlaybackStore::save(const PlaybackState&s){if(!db_||s.mediaId.empty())return false;auto x=sanitizePlaybackState(s);sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO playback_state VALUES(?,?,?,?,?) ON CONFLICT(media_id) DO UPDATE SET position_ms=excluded.position_ms,speed=excluded.speed,volume=excluded.volume,paused=excluded.paused",-1,&st,nullptr);sqlite3_bind_text(st,1,x.mediaId.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(st,2,x.positionMs);sqlite3_bind_double(st,3,x.speed);sqlite3_bind_int(st,4,x.volume);sqlite3_bind_int(st,5,x.paused);bool ok=sqlite3_step(st)==SQLITE_DONE;sqlite3_finalize(st);return ok;}PlaybackState PlaybackStore::load(const std::string&id)const{PlaybackState s;s.mediaId=id;if(!db_)return s;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"SELECT position_ms,speed,volume,paused FROM playback_state WHERE media_id=?",-1,&st,nullptr);sqlite3_bind_text(st,1,id.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(st)==SQLITE_ROW){s.positionMs=sqlite3_column_int64(st,0);s.speed=sqlite3_column_double(st,1);s.volume=sqlite3_column_int(st,2);s.paused=sqlite3_column_int(st,3);}sqlite3_finalize(st);return sanitizePlaybackState(s);}std::string PlaybackStore::lastError()const{return error_;}
void MediaQueue::setItems(std::vector<MediaItem>v){items_=std::move(v);current_=0;hasCurrent_=!items_.empty();}void MediaQueue::append(const MediaItem&m){items_.push_back(m);if(!hasCurrent_)hasCurrent_=true;}void MediaQueue::clear(){items_.clear();hasCurrent_=false;current_=0;}const MediaItem*MediaQueue::current()const{return hasCurrent_?&items_[current_]:nullptr;}const MediaItem*MediaQueue::next(){if(!hasCurrent_||current_+1>=items_.size())return nullptr;return &items_[++current_];}const MediaItem*MediaQueue::previous(){if(!hasCurrent_||!current_)return nullptr;return &items_[--current_];}bool MediaQueue::moveTo(std::size_t i){if(i>=items_.size())return false;current_=i;hasCurrent_=true;return true;}bool MediaQueue::contains(const std::string&id)const{for(auto&m:items_)if(m.id==id)return true;return false;}std::size_t MediaQueue::size()const{return items_.size();}
HistoryStore::HistoryStore(const std::string&p):path_(p){}HistoryStore::~HistoryStore(){if(db_)sqlite3_close(db_);}bool HistoryStore::open(){return sqlite3_open(path_.c_str(),&db_)==SQLITE_OK&&ex(db_,"CREATE TABLE IF NOT EXISTS history(id TEXT PRIMARY KEY,title TEXT,path TEXT,position_ms INTEGER,play_count INTEGER,last_played INTEGER);");}bool HistoryStore::record(const MediaItem&m,std::int64_t pos){if(!db_||m.id.empty())return false;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO history VALUES(?,?,?,?,1,strftime('%s','now')) ON CONFLICT(id) DO UPDATE SET position_ms=excluded.position_ms,play_count=history.play_count+1,last_played=excluded.last_played",-1,&st,nullptr);auto p=m.path.string();sqlite3_bind_text(st,1,m.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,2,m.title.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,3,p.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(st,4,std::max<std::int64_t>(0,pos));bool ok=sqlite3_step(st)==SQLITE_DONE;sqlite3_finalize(st);return ok;}std::vector<HistoryEntry>HistoryStore::recent(std::size_t n)const{std::vector<HistoryEntry>v;if(!db_)return v;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"SELECT id,title,path,position_ms,play_count FROM history ORDER BY last_played DESC LIMIT ?",-1,&st,nullptr);sqlite3_bind_int(st,1,(int)std::min<std::size_t>(n,10000));while(sqlite3_step(st)==SQLITE_ROW)v.push_back({(const char*)sqlite3_column_text(st,0),(const char*)sqlite3_column_text(st,1),(const char*)sqlite3_column_text(st,2),sqlite3_column_int64(st,3),sqlite3_column_int(st,4)});sqlite3_finalize(st);return v;}std::string HistoryStore::lastError()const{return error_;}
PlaylistStore::PlaylistStore(const std::string&p):path_(p){}PlaylistStore::~PlaylistStore(){if(db_)sqlite3_close(db_);}bool PlaylistStore::open(){if(sqlite3_open(path_.c_str(),&db_)!=SQLITE_OK)return false;return ex(db_,"CREATE TABLE IF NOT EXISTS playlists(id TEXT PRIMARY KEY,name TEXT);CREATE TABLE IF NOT EXISTS playlist_items(playlist_id TEXT,media_id TEXT,position INTEGER,PRIMARY KEY(playlist_id,media_id));");}bool PlaylistStore::save(const Playlist&p){if(!db_||p.id.empty()||p.name.empty())return false;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO playlists VALUES(?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name",-1,&st,nullptr);sqlite3_bind_text(st,1,p.id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,2,p.name.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(st)==SQLITE_DONE;sqlite3_finalize(st);return ok;}bool PlaylistStore::addItem(const std::string&p,const std::string&m){if(!db_||p.empty()||m.empty())return false;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT OR IGNORE INTO playlist_items VALUES(?,?,COALESCE((SELECT MAX(position)+1 FROM playlist_items WHERE playlist_id=?),0))",-1,&st,nullptr);sqlite3_bind_text(st,1,p.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,2,m.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,3,p.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(st)==SQLITE_DONE;sqlite3_finalize(st);return ok;}std::vector<Playlist>PlaylistStore::list()const{std::vector<Playlist>v;if(!db_)return v;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"SELECT id,name FROM playlists",-1,&st,nullptr);while(sqlite3_step(st)==SQLITE_ROW)v.push_back({(const char*)sqlite3_column_text(st,0),(const char*)sqlite3_column_text(st,1),{}});sqlite3_finalize(st);return v;}
SettingsStore::SettingsStore(const std::string&p):path_(p){}SettingsStore::~SettingsStore(){if(db_)sqlite3_close(db_);}bool SettingsStore::open(){return sqlite3_open(path_.c_str(),&db_)==SQLITE_OK&&ex(db_,"CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);");}bool SettingsStore::set(const std::string&k,const std::string&v){if(!db_||k.empty())return false;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",-1,&st,nullptr);sqlite3_bind_text(st,1,k.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(st,2,v.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(st)==SQLITE_DONE;sqlite3_finalize(st);return ok;}std::string SettingsStore::get(const std::string&k,const std::string&f)const{if(!db_)return f;sqlite3_stmt*st=nullptr;sqlite3_prepare_v2(db_,"SELECT value FROM settings WHERE key=?",-1,&st,nullptr);sqlite3_bind_text(st,1,k.c_str(),-1,SQLITE_TRANSIENT);std::string v=f;if(sqlite3_step(st)==SQLITE_ROW)v=(const char*)sqlite3_column_text(st,0);sqlite3_finalize(st);return v;}
PlayerSession::PlayerSession(std::unique_ptr<PlaybackEngine>e,PlaybackStore&p,HistoryStore&h):engine_(std::move(e)),playback_(p),history_(h){}bool PlayerSession::saveCurrent(){if(!hasCurrent_)return true;return playback_.save({current_.id,controller_.positionMs(),controller_.speed(),controller_.volume(),!controller_.playing()});}bool PlayerSession::open(const MediaItem&m){if(m.id.empty()||!controller_.load(m.path.string(),m.durationMs))return false;if(!engine_->play(m.path.string()))return false;current_=m;hasCurrent_=true;auto s=playback_.load(m.id);controller_.seek(s.positionMs);controller_.setSpeed(s.speed);controller_.setVolume(s.volume);if(s.paused)engine_->pause();return true;}bool PlayerSession::play(){return hasCurrent_&&engine_->play(current_.path.string())&&controller_.play();}bool PlayerSession::pause(){return hasCurrent_&&engine_->pause()&&controller_.pause();}bool PlayerSession::stop(){return hasCurrent_&&engine_->stop()&&controller_.stop();}bool PlayerSession::seek(std::int64_t p){return hasCurrent_&&engine_->seek(p)&&controller_.seek(p);}bool PlayerSession::setSpeed(double s){return hasCurrent_&&engine_->setSpeed(s)&&controller_.setSpeed(s);}bool PlayerSession::setVolume(int v){return hasCurrent_&&engine_->setVolume(v)&&controller_.setVolume(v);}const MediaItem*PlayerSession::current()const{return hasCurrent_?&current_:nullptr;}const MediaItem*PlayerSession::next(){auto n=queue_.next();return n&&open(*n)?n:nullptr;}const MediaItem*PlayerSession::previous(){auto n=queue_.previous();return n&&open(*n)?n:nullptr;}bool PlayerSession::saveState(){return saveCurrent();}bool PlayerSession::recordHistory(){return hasCurrent_&&history_.record(current_,controller_.positionMs());}MediaQueue&PlayerSession::queue(){return queue_;}
}
